### ISSUE TITLE
line values without quotes are skipped

### ISSUE THREAD

**Issue by rococodogs** [LafayetteCollegeLibraries/webvtt-cli#5]
with the given csv rows

```csv
Timestamp,Speaker,Text
00:29:54–00:29:57,Interviewer,"OK. So, Winston, are you married? "
00:29:57–00:29:58,Speaker,Yes. Yes I am.
00:29:58–00:30:00,Interviewer,And what’s your wife’s name?
00:30:00–00:30:01,Speaker,Her name is Robin.
00:30:01–00:30:03,Interviewer,"OK, and do you guys have kids? "
```

the lines that don't contain quotes are skipped:

```vtt
WEBVTT

00:29:54.000 --> 00:29:57.000
<v Interviewer>OK. So, Winston, are you married? </v>

00:29:57.000 --> 00:29:58.000
<v Speaker></v>

00:29:58.000 --> 00:30:00.000
<v Interviewer></v>

00:30:00.000 --> 00:30:01.000
<v Speaker></v>

00:30:01.000 --> 00:30:03.000
<v Interviewer>OK, and do you guys have kids? </v>
```

looks like the related code is: https://github.com/LafayetteCollegeLibraries/webvtt-cli/blob/main/src/csvrow.cpp#L44-L51

**Comment by jacksodl23** [comment]
> 00:29:54–00:29:57,Interviewer,"OK. So, Winston, are you married? "**,**
00:29:57–00:29:58,Speaker,Yes. Yes I am.**,**
00:29:58–00:30:00,Interviewer,And what’s your wife’s name?  **,**
00:30:00–00:30:01,Speaker,Her name is Robin.**,**
00:30:01–00:30:03,Interviewer,"OK, and do you guys have kids? "**,**

I'm not entirely sure what the culprit is yet, but I noticed that these trailing commas were not in the other CSVs I had been testing. I'll investigate this further.
